#!/usr/bin/env bash
# SudoCode CHM — Render the dashboard from a JSON snapshot.
# Usage: ./scripts/chm_report.sh [snapshot.json]
#
# Generates a human-readable Markdown report from the CHM snapshot.
# Does NOT require mustache/handlebars — uses pure bash + jq.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SNAPSHOT="${1:-$WORKSPACE_ROOT/target/chm/snapshot.json}"
OUT="${CHM_REPORT_OUT:-$WORKSPACE_ROOT/target/chm/dashboard.md}"

if [ ! -f "$SNAPSHOT" ]; then
  echo "Error: snapshot not found at $SNAPSHOT" >&2
  echo "Run ./scripts/chm_scan.sh first." >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "Error: jq is required. Install with: brew install jq" >&2
  exit 1
fi

info() { printf '\033[1;34m[CHM]\033[0m %s\n' "$*"; }

# Read values from snapshot
TS=$(jq -r '.timestamp' "$SNAPSHOT")
WS=$(jq -r '.workspace' "$SNAPSHOT")
LINT_W=$(jq '.lints.warnings' "$SNAPSHOT")
LINT_E=$(jq '.lints.errors' "$SNAPSHOT")
RUST_LINES=$(jq '.volume.rust_lines' "$SNAPSHOT")
TOTAL_FILES=$(jq '.volume.total_files' "$SNAPSHOT")
TOTAL_LINES=$(jq '.volume.total_lines' "$SNAPSHOT")
MONOLITH_THRESH=$(jq '.monolith_watch.threshold_loc' "$SNAPSHOT")
MONOLITH_COUNT=$(jq '.monolith_watch.count' "$SNAPSHOT")
CHECK_MS=$(jq '.speed_watch.incremental_check_ms' "$SNAPSHOT")
TEST_COUNT=$(jq '.tests.test_count' "$SNAPSHOT")
TEST_FILES=$(jq '.tests.test_file_count' "$SNAPSHOT")
COV_PCT=$(jq '.coverage.line_pct' "$SNAPSHOT")

# Build monolith table rows
MONOLITH_ROWS=$(jq -r '.monolith_watch.files[] | "| \(.lines) | `\(.file)` |"' "$SNAPSHOT" 2>/dev/null || echo "")

# Build lint codes table rows
LINT_ROWS=$(jq -r '.lints.top_codes[] | "| `\(.code)` | \(.count) |"' "$SNAPSHOT" 2>/dev/null || echo "")

# Build uncovered files list
UNCOV_LIST=$(jq -r '.coverage.uncovered_files[]? | "- `\(.)`"' "$SNAPSHOT" 2>/dev/null || echo "")

# Speed assessment
if [ "$CHECK_MS" -lt 5000 ] 2>/dev/null; then
  SPEED_BADGE="Excellent"
elif [ "$CHECK_MS" -lt 15000 ] 2>/dev/null; then
  SPEED_BADGE="Acceptable"
else
  SPEED_BADGE="Slow"
fi

# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------

cat > "$OUT" <<EOF
# SudoCode Health Dashboard

> Generated: $TS
> Workspace: \`$WS\`

---

## Monolith Watch

Files exceeding **$MONOLITH_THRESH LOC** are refactor candidates.

| Lines | File |
|------:|------|
$MONOLITH_ROWS

**$MONOLITH_COUNT file(s)** above threshold.

---

## Lint Summary

| Metric | Count |
|--------|------:|
| Clippy warnings | $LINT_W |
| Clippy errors   | $LINT_E |

EOF

if [ -n "$LINT_ROWS" ]; then
cat >> "$OUT" <<EOF
### Top Lint Codes
| Code | Occurrences |
|------|------------:|
$LINT_ROWS

EOF
fi

cat >> "$OUT" <<EOF
---

## Unchecked Complexity

| Metric | Value |
|--------|------:|
| Total \`#[test]\` functions | $TEST_COUNT |
| Files with tests          | $TEST_FILES |
| Line coverage             | $COV_PCT |

EOF

if [ -n "$UNCOV_LIST" ]; then
cat >> "$OUT" <<EOF
### Files with 0% Coverage
$UNCOV_LIST

EOF
fi

cat >> "$OUT" <<EOF
---

## Speed Watch

| Metric | Value |
|--------|------:|
| Incremental \`cargo check\` | ${CHECK_MS} ms |
| Assessment | **$SPEED_BADGE** |

---

## Volume Overview

| Metric | Value |
|--------|------:|
| Rust lines of code | $RUST_LINES |
| Total files         | $TOTAL_FILES |
| Total lines         | $TOTAL_LINES |

---

*Generated by SudoCode CHM*
EOF

info "Dashboard written to $OUT"
